name: datadescribe
channels:
  - defaults
  - conda-forge
dependencies:
  - python==3.7
  - pandas==0.24.0
  - numpy==1.16.0
  - scipy==1.1.0
  - seaborn==0.9.0
  - scikit-learn==0.23
  - gensim==3.4.0
  - pyldavis==2.1.2
  - shapely==1.6.4
  - nltk==3.4
  - gcsfs==0.2.1
  - geopandas==0.5.0
  - hdbscan==0.8.20
  - jupyterlab==0.35.4
  - ipykernel==5.1.0
  - geoplot==0.2.4
  - ipython==7.5.0
  - xlrd==1.2.0
  - paramiko==2.4.2
  - descartes=1.1.0
  - tqdm>=4.49.0
  - pip:
      - google-cloud-storage==1.18.0
      - presidio-analyzer==0.3.8917rc0
