name: doc-env
channels:
  - defaults
  - conda-forge
dependencies:
  - python==3.7
  - pandas>=0.24.0
  - numpy>=1.15.4
  - scipy>=1.1.0
  - seaborn>=0.9.0
  - matplotlib<=3.3.0
  - scikit-learn>=0.20.3
  - gensim>=3.4.0
  - pyldavis>=2.1.2
  - eli5>=0.8.1
  - shapely>=1.6.4
  - nltk>=3.4
  - ipython>=7.5.0
  - gcsfs>=0.2.1
  - hdbscan>=0.8.20
  - ipython>=7.5.0
  - xlrd>=1.2.0
  - paramiko>=2.4.2
  - plotly>=3.8.1
  - dask>=2.17.2
  - pip>=20.0.2
  - papermill>=2.1.2
  - sphinx==3.1.2
  - nbsphinx==0.7.1
  - sphinx-autoapi==1.4.0
  - tqdm>=4.49.0
  - pip:
      - google-cloud-storage>=1.18.0
      - presidio-analyzer==0.3.8917rc0
      - git+https://github.com/modin-project/modin
      - sphinx-rtd-theme>=0.5.0
      - sphinx-multiversion==0.2.4
